version: '2'
services:

    datastore:
        image: timtosi/sql:latest
        entrypoint:
            - /usr/bin/mysqld.sh
        command:
            - --basedir=/usr
            - --bind-address=0.0.0.0
            - --concurrent_insert=2
            - --datadir=/var/lib/mysql
            - --join_buffer_size=2M
            - --key_buffer_size=128M
            - --low-priority-updates=1
            - --max_allowed_packet=16M
            - --max_connections=400
            - --max_heap_table_size=256M
            - --myisam_sort_buffer_size=64M
            - --pid-file=/var/run/mysqld/mysqld.pid
            - --port=3306
            - --query_cache_limit=1M
            - --query_cache_size=16M
            - --read_buffer_size=1024K
            - --read_rnd_buffer_size=4096K
            - --skip-grant-tables
            - --socket=/var/run/mysqld/mysqld.sock
            - --sort_buffer_size=1024K
            - --thread_cache_size=8
            - --thread_stack=128K
            - --tmpdir=/tmp
            - --tmp_table_size=512M
            - --transaction-isolation=READ-COMMITTED
            - --user=mysql
            - --wait_timeout=60
        hostname: datastore-01
        ports:
            - "33306:3306"
            - "9090:9090"
        volumes:
            - "${PWD}/initdb:/initdb"
        environment:
            - MYSQL_USER=root
            - MYSQL_PASS=ok
            - MYSQL_PROTO=tcp
            - MYSQL_DB_NAME=fishfinger
